### ISSUE TITLE
message_bus:message_bus_24: ERROR (spawn error)

### ISSUE THREAD

**Issue by VAVASIN** [koshelevsergey/cops-cli#6]
![image](https://user-images.githubusercontent.com/45480141/126942179-7e4e84d1-4096-4744-89c6-517d94e74c18.png)

**Comment by koshelevsergey** [comment]
Ага, я так понимаю supervisord из-за авто старта, запустился до момента когда был доступен RabbitMQ.
Да, логично что посыпались ошибки, не предусмотрел этого.
